### ISSUE TITLE
Gap-free recordings shouldn't use "sweep" notation

### ISSUE THREAD

**Issue by saglag** [swharden/ABFview#3]
https://github.com/swharden/ABFview/blob/5ffe3036333862aedbcf21346327a6651dc0cece/src/ABFview/EphysPlot.cs#L20 

Gap-free recordings display "Sweep 1 of 0". Perhaps use alternate notation using if/else or switch statements?

**Comment by swharden** [comment]
Good idea! I'll put this in soon.

lol @ the other issues that sat here open for almost 3 years 😅
